Update gitian-building.md
bitcoin-core/docs pull request #66
Opened 2020-11-29 05:20 UTC by miketwenty1

fixing typo

2020-11-29 08:54 UTC, hebasto requested changes
Concept ACK 93dc9ff1b529276e78e6f031c786b774997b39bc.

Also I'd suggest to use long versions of arguments in documentation, i.e.:
- s/`-b`/`--build`/
- s/`-s`/`--sign`/

2020-11-29 08:54 UTC, hebasto commented on gitian-building.md
> + `./gitian-build.py --detach-sign -s $NAME $VERSION --no-commit`
```suggestion
 `./gitian-build.py --detach-sign --no-commit -s $NAME $VERSION`
```

to be consistent with the previous
https://github.com/bitcoin-core/docs/blob/93dc9ff1b529276e78e6f031c786b774997b39bc/gitian-building.md#L87

2020-11-30 15:35 UTC, hebasto commented
LGTM, mind [squashing](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) two commits into single one?

2020-12-01 18:44 UTC, miketwenty1 commented
@hebasto np, done.

2020-12-01 19:21 UTC, jonasschnelli commented
Verified (https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-build.py#L171).
utACK aafd085961bcdf4c0cd1efb6c823c63c37a07a02

2020-12-01 20:11 UTC, hebasto approved these changes
ACK aafd085961bcdf4c0cd1efb6c823c63c37a07a02, I have reviewed the code and it looks OK, I agree it can be merged.

2020-12-02 11:00 UTC, merged